---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: KubeadmControlPlane
metadata:
  name: ${CLUSTER_NAME}-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    files:
    - contentFrom:
        secret:
          name: azure-secret
          key: azure.json
      owner: root:root
      path: /etc/kubernetes/azure.json
